version: '3.8'

services:
  broadcast-channel:
    image: postgres:16
    hostname: broadcast-channel
    container_name: broadcast-channel
    environment:
      - POSTGRES_USER=${BROADCAST_CHANNEL_USER}
      - POSTGRES_PASSWORD=${BROADCAST_CHANNEL_PASSWORD}
      - POSTGRES_DB=${BROADCAST_CHANNEL_DATABASE}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      internal:
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${BROADCAST_CHANNEL_USER}']
      interval: 10s
      start_period: 30s
      timeout: 10s
      retries: 3

  opal-server:
    image: permitio/opal-server:0.7.5
    hostname: opal-server
    container_name: opal-server
    environment:
      - OPAL_BROADCAST_URI=${OPAL_BROADCAST_URI}
      - UVICORN_NUM_WORKERS=${UVICORN_NUM_WORKERS}
      - OPAL_POLICY_REPO_URL=${OPAL_POLICY_REPO_URL}
      - OPAL_POLICY_REPO_MAIN_BRANCH=${OPAL_POLICY_REPO_MAIN_BRANCH}
      - OPAL_POLICY_REPO_SSH_KEY=${OPAL_POLICY_REPO_SSH_KEY}
      - OPAL_POLICY_REPO_POLLING_INTERVAL=${OPAL_POLICY_REPO_POLLING_INTERVAL}
      - OPAL_DATA_CONFIG_SOURCES=${OPAL_DATA_CONFIG_SOURCES}
    ports:
      - "7002:7002"
    networks:
      internal:
        ipv4_address: ${OPAL_SERVER_IP}
    depends_on:
      broadcast-channel:
        condition: service_healthy
  
  opal-client-1:
    image: permitio/opal-client:0.7.5
    hostname: opal-client-1
    container_name: opal-client-1
    environment:
      - OPAL_SERVER_URL=${OPAL_SERVER_URL}
      - OPAL_DATA_TOPICS=${OPAL_DATA_TOPICS_1}
    ports:
      - "9001:7000"
      - "9081:8181"
    networks:
      internal:
    depends_on:
      opal-server:
        condition: service_started
  
  opal-client-2:
    image: permitio/opal-client:0.7.5
    hostname: opal-client-2
    container_name: opal-client-2
    environment:
      - OPAL_SERVER_URL=${OPAL_SERVER_URL}
      - OPAL_DATA_TOPICS=${OPAL_DATA_TOPICS_2}
    ports:
      - "9002:7000"
      - "9082:8181"
    networks:
      internal:
    depends_on:
      opal-server:
        condition: service_started

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: ${INTERNAL_SUBNET}

volumes:
  postgres-data:
